version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions-minor-patch:
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip-minor-patch:
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-minor-patch:
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      docker-client-minor-patch:
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps"
