<#
.SYNOPSIS
    Dugout Ralph Watchdog — nightly autonomous audit+heal runner.

.DESCRIPTION
    Runs ./ralph.sh 10 inside the Dugout project, captures the execution summary,
    detects SIGN-008 (3-strike rollback) or outright failure, and POSTs a JSON
    report to the n8n watchdog webhook on the Pi for Telegram fan-out.

.NOTES
    Scheduled via Windows Task Scheduler (see README for schtasks command).
    Requires: git, claude CLI on PATH, bash (Git Bash or WSL).
#>

param(
    [string]$ProjectRoot = "H:\Projects\PCLL\Dugout",
    [int]$Iterations = 10,
    [string]$WebhookUrl = "https://n8n.joelycannoli.com/webhook/dugout-ralph-watchdog",
    [string]$LogDir = "$env:USERPROFILE\Logs\ralph-dugout"
)

$ErrorActionPreference = "Continue"

# --- Setup ---
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Force -Path $LogDir | Out-Null }
$ts = Get-Date -Format "yyyy-MM-dd_HHmmss"
$logFile = Join-Path $LogDir "ralph-$ts.log"
$started = Get-Date

Set-Location $ProjectRoot

# --- Snapshot pre-state ---
$preCommit = (git rev-parse HEAD 2>$null) | Out-String | ForEach-Object { $_.Trim() }
$branch    = (git rev-parse --abbrev-ref HEAD 2>$null) | Out-String | ForEach-Object { $_.Trim() }

# --- Run Ralph ---
# Use bash to execute ralph.sh (comes with Git for Windows or WSL)
$bashPath = (Get-Command bash -ErrorAction SilentlyContinue).Source
if (-not $bashPath) { $bashPath = "C:\Program Files\Git\bin\bash.exe" }

$runOutput = & $bashPath -c "cd `"$ProjectRoot`" && ./ralph.sh $Iterations" 2>&1 | Tee-Object -FilePath $logFile
$exitCode  = $LASTEXITCODE

# --- Post-state ---
$postCommit  = (git rev-parse HEAD 2>$null) | Out-String | ForEach-Object { $_.Trim() }
$commitsMade = if ($preCommit -and $postCommit -and $preCommit -ne $postCommit) {
    (git log --oneline "$preCommit..$postCommit" 2>$null) -join "`n"
} else { "" }
$gitStatus = (git status --porcelain 2>$null) -join "`n"
$duration  = [int]((Get-Date) - $started).TotalSeconds

# --- Classify severity ---
$textAll = ($runOutput | Out-String)
$sign008Hit  = $textAll -match "SIGN-008" -or $textAll -match "MAX ITERATIONS REACHED"
$complete    = $textAll -match "<promise>COMPLETE</promise>"
$blockerHit  = $textAll -match "blocker" -or $textAll -match "rollback"

$severity = if ($sign008Hit -or $exitCode -ne 0 -or $blockerHit) { "critical" }
            elseif ($complete) { "success" }
            else { "warning" }

# --- Grab last 40 lines as the human-readable summary ---
$tail = ($runOutput | Select-Object -Last 40) -join "`n"

# --- Auto-PR on success (branch push only — never main push) ---
$prUrl = ""
$prBranch = ""
if ($severity -eq "success" -and $commitsMade -ne "" -and $branch -eq "main") {
    $shortSha = (git rev-parse --short HEAD 2>$null) | Out-String | ForEach-Object { $_.Trim() }
    $prBranch = "full-send/{0}-{1}" -f (Get-Date -Format "yyyy-MM-dd-HHmmss"), $shortSha

    # Verify gh CLI is authed before attempting
    $ghOk = $true
    try { & gh auth status 2>&1 | Out-Null; if ($LASTEXITCODE -ne 0) { $ghOk = $false } }
    catch { $ghOk = $false }

    if ($ghOk) {
        # Reset main back to preCommit so we don't push fixes to main directly
        & git checkout -b $prBranch | Out-Null
        & git checkout main | Out-Null
        & git reset --hard $preCommit | Out-Null
        & git checkout $prBranch | Out-Null

        $pushResult = & git push -u origin $prBranch 2>&1
        if ($LASTEXITCODE -eq 0) {
            $prBody = @"
## FULL SEND — Autonomous Audit & Heal

**Run timestamp:** $($started.ToString("u"))
**Duration:** ${duration}s
**Iterations used:** $Iterations
**Host:** $($env:COMPUTERNAME)

### Commits
``````
$commitsMade
``````

### Tail of execution log
``````
$tail
``````

_Generated by Dugout Ralph Watchdog. Review the diff, then merge from your phone if it looks clean._
"@
            $bodyFile = Join-Path $env:TEMP "ralph-pr-body-$ts.md"
            Set-Content -Path $bodyFile -Value $prBody -Encoding UTF8
            $prCreate = & gh pr create --base main --head $prBranch `
                          --title "FULL SEND: $(Get-Date -Format 'yyyy-MM-dd') autonomous audit" `
                          --body-file $bodyFile 2>&1
            if ($LASTEXITCODE -eq 0) {
                $prUrl = ($prCreate | Select-String -Pattern "https://github.com/" | Select-Object -First 1).ToString().Trim()
                Write-Host "[watchdog] PR opened: $prUrl"
            } else {
                Write-Warning "[watchdog] gh pr create failed: $prCreate"
            }
        } else {
            Write-Warning "[watchdog] git push failed: $pushResult"
        }
    } else {
        Write-Warning "[watchdog] gh CLI not authenticated; skipping auto-PR. Run: gh auth login"
    }
}

# --- Payload ---
$payload = @{
    project       = "dugout-portal"
    host          = $env:COMPUTERNAME
    branch        = $branch
    severity      = $severity
    complete      = [bool]$complete
    sign_008_hit  = [bool]$sign008Hit
    exit_code     = $exitCode
    duration_sec  = $duration
    iterations    = $Iterations
    commits_made  = $commitsMade
    git_status    = $gitStatus
    summary_tail  = $tail
    log_path      = $logFile
    started_at    = $started.ToString("o")
    finished_at   = (Get-Date).ToString("o")
    pr_url        = $prUrl
    pr_branch     = $prBranch
} | ConvertTo-Json -Depth 4 -Compress

# --- POST to n8n ---
try {
    Invoke-RestMethod -Uri $WebhookUrl `
                      -Method Post `
                      -Body $payload `
                      -ContentType "application/json" `
                      -TimeoutSec 30 | Out-Null
    Write-Host "[watchdog] reported severity=$severity to n8n"
} catch {
    Write-Warning "[watchdog] failed to reach n8n webhook: $_"
    Add-Content -Path $logFile -Value "WATCHDOG WEBHOOK FAILURE: $_"
}

exit $exitCode
