#!/usr/bin/env bash
# Dugout Ralph Watchdog — nightly autonomous audit+heal runner (macOS / Linux)
# Runs ./ralph.sh, reports outcome to n8n watchdog webhook for Telegram fan-out.
#
# Schedule via crontab. Example (2:00 AM nightly):
#   0 2 * * * /Users/joel/code/Dugout/scripts/ralph-watchdog.sh >> /tmp/ralph-cron.log 2>&1

set -uo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$HOME/code/Dugout}"
ITERATIONS="${ITERATIONS:-10}"
WEBHOOK_URL="${WEBHOOK_URL:-https://n8n.joelycannoli.com/webhook/dugout-ralph-watchdog}"
LOG_DIR="${LOG_DIR:-$HOME/Logs/ralph-dugout}"

mkdir -p "$LOG_DIR"
TS="$(date +%Y-%m-%d_%H%M%S)"
LOG_FILE="$LOG_DIR/ralph-$TS.log"
STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
STARTED_EPOCH="$(date +%s)"

cd "$PROJECT_ROOT" || { echo "[watchdog] project root not found: $PROJECT_ROOT"; exit 2; }

# Snapshot pre-state
PRE_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo '')"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"

# Run Ralph (tee to log)
./ralph.sh "$ITERATIONS" 2>&1 | tee "$LOG_FILE"
EXIT_CODE="${PIPESTATUS[0]}"

# Post-state
POST_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo '')"
COMMITS_MADE=""
if [ -n "$PRE_COMMIT" ] && [ -n "$POST_COMMIT" ] && [ "$PRE_COMMIT" != "$POST_COMMIT" ]; then
    COMMITS_MADE="$(git log --oneline "${PRE_COMMIT}..${POST_COMMIT}" 2>/dev/null | tr '\n' '|')"
fi
GIT_STATUS="$(git status --porcelain 2>/dev/null | tr '\n' '|')"
DURATION="$(( $(date +%s) - STARTED_EPOCH ))"
FINISHED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Classify severity
SIGN_008_HIT="false"; COMPLETE="false"; BLOCKER_HIT="false"
grep -q "SIGN-008\|MAX ITERATIONS REACHED" "$LOG_FILE" && SIGN_008_HIT="true"
grep -q "<promise>COMPLETE</promise>" "$LOG_FILE" && COMPLETE="true"
grep -qi "blocker\|rollback" "$LOG_FILE" && BLOCKER_HIT="true"

if [ "$SIGN_008_HIT" = "true" ] || [ "$EXIT_CODE" -ne 0 ] || [ "$BLOCKER_HIT" = "true" ]; then
    SEVERITY="critical"
elif [ "$COMPLETE" = "true" ]; then
    SEVERITY="success"
else
    SEVERITY="warning"
fi

# Grab last 40 lines as summary
SUMMARY_TAIL="$(tail -n 40 "$LOG_FILE" | jq -Rs .)"
COMMITS_JSON="$(echo "$COMMITS_MADE" | jq -Rs .)"
STATUS_JSON="$(echo "$GIT_STATUS" | jq -Rs .)"

# --- Auto-PR on success (branch push only — never main push) ---
PR_URL=""
PR_BRANCH=""
if [ "$SEVERITY" = "success" ] && [ -n "$COMMITS_MADE" ] && [ "$BRANCH" = "main" ]; then
    SHORT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
    PR_BRANCH="full-send/$(date +%Y-%m-%d-%H%M%S)-${SHORT_SHA}"

    if gh auth status >/dev/null 2>&1; then
        # Carve commits onto a feature branch; reset main back to pre-state
        git checkout -b "$PR_BRANCH" >/dev/null 2>&1
        git checkout main >/dev/null 2>&1
        git reset --hard "$PRE_COMMIT" >/dev/null 2>&1
        git checkout "$PR_BRANCH" >/dev/null 2>&1

        if git push -u origin "$PR_BRANCH" >/dev/null 2>&1; then
            BODY_FILE="/tmp/ralph-pr-body-${TS}.md"
            cat > "$BODY_FILE" <<BODY
## FULL SEND — Autonomous Audit & Heal

**Run timestamp:** $STARTED_AT
**Duration:** ${DURATION}s
**Iterations used:** $ITERATIONS
**Host:** $(hostname)

### Commits
\`\`\`
$(echo "$COMMITS_MADE" | tr '|' '\n')
\`\`\`

### Tail of execution log
\`\`\`
$(tail -n 40 "$LOG_FILE")
\`\`\`

_Generated by Dugout Ralph Watchdog. Review the diff, then merge from your phone if it looks clean._
BODY
            PR_URL="$(gh pr create \
                --base main --head "$PR_BRANCH" \
                --title "FULL SEND: $(date +%Y-%m-%d) autonomous audit" \
                --body-file "$BODY_FILE" 2>/dev/null | grep -Eo 'https://github\.com/[^ ]+' | head -1)"
            [ -n "$PR_URL" ] && echo "[watchdog] PR opened: $PR_URL"
        else
            echo "[watchdog] git push of $PR_BRANCH failed; skipping PR" | tee -a "$LOG_FILE"
        fi
    else
        echo "[watchdog] gh CLI not authenticated; skipping auto-PR. Run: gh auth login" | tee -a "$LOG_FILE"
    fi
fi

# Build payload
PAYLOAD=$(cat <<EOF
{
  "project": "dugout-portal",
  "host": "$(hostname)",
  "branch": "$BRANCH",
  "severity": "$SEVERITY",
  "complete": $COMPLETE,
  "sign_008_hit": $SIGN_008_HIT,
  "exit_code": $EXIT_CODE,
  "duration_sec": $DURATION,
  "iterations": $ITERATIONS,
  "commits_made": $COMMITS_JSON,
  "git_status": $STATUS_JSON,
  "summary_tail": $SUMMARY_TAIL,
  "log_path": "$LOG_FILE",
  "started_at": "$STARTED_AT",
  "finished_at": "$FINISHED_AT",
  "pr_url": "$PR_URL",
  "pr_branch": "$PR_BRANCH"
}
EOF
)

# POST to n8n
if curl -fsS -X POST -H "Content-Type: application/json" \
     --max-time 30 \
     -d "$PAYLOAD" \
     "$WEBHOOK_URL" > /dev/null; then
    echo "[watchdog] reported severity=$SEVERITY to n8n"
else
    echo "[watchdog] WARN: webhook POST failed" | tee -a "$LOG_FILE"
fi

exit "$EXIT_CODE"
